name: pycftboot-docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate docs
      run: |
        pip install sphinx sphinx-rtd-theme myst-parser
        cd docs
        make html
    - name: publish docs
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: docs
        folder: docs/build/html
