name: pycftboot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10-slim
    steps:
      - uses: actions/checkout@v2
      - name: install build and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build coverage
      - name: build package
        run: |
          python -m build
      - name: install pycftboot
        run: |
          VERSION=$(python -c "from pkg_resources import get_distribution; print(get_distribution('pycftboot').version)")
          pip install dist/pycftboot-${VERSION}.tar.gz
      - name: make tests and generate coverage report
        run: |
          coverage run -m unittest
          coverage xml
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
