name: pycftboot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10-slim
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: build package
        run: |
          python -m build
