name: pycftboot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10-slim
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: build package
        run: |
          python -m build
      - name: upload built package
        uses: actions/upload-artifact@v3
        with:
          name: dist-pycftboot
          path: |
            dist

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: wlandry/sdpb:2.5.1
    steps:
      - uses: actions/checkout@v2
      - name: install pip and test dependencies
        run: |
          apt-get -qq -o=Dpkg::Use-Pty=0 update
          apt-get -qq -o=Dpkg::Use-Pty=0 install -y python3-pip
          pip3 install coverage
      - name: download built package
        uses: actions/download-artifact@v3
        with:
          name: dist-pycftboot
          path: dist
      - name: install pycftboot and its dependencies
        run: |
          ls -lash
          pip3 install dist/pycftboot-0.0.1.tar.gz
      - name: make tests and generate coverage report
        run: |
          coverage run -m unittest
          coverage xml
      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-xml
          path: |
            coverage.xml

  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report-xml
      - uses: codecov/codecov-action@v2
