name: pycftboot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10-slim
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: build package
        run: |
          python -m build

  test:
    runs-on: ubuntu-latest
    container:
      image: wlandry/sdpb:2.5.1
    steps:
      - uses: actions/checkout@v2
      - name: install pip and test dependencies
        run: |
          apt-get update -qq
          apt-get install -yqq python3-pip
          pip install coverage
      - name: make tests and generate coverage report
        run: |
          coverage run -m unittest
          coverage xml
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
